fetcher:
  source: https://api.snyk.io/rest/openapi
  destination: docs/.gitbook/assets/rest-spec.json
specs:
- path: docs/.gitbook/assets/spec.yaml
  suffix: " (v1)"
  docsHint: This document uses the v1 API. For more details, see the [v1 API](../v1-api-overview/).
- path: docs/.gitbook/assets/rest-spec.json
  docsHint: This document uses the REST API. For more details, see the [Authentication for API](../authentication-for-api/) page.
categoryContext:
- name: licenses-v1
  hint: |
    **Note:** When you import or update Projects, changes will be reflected in the endpoint results after a one-hour delay.
output:
  apiReferencePath: docs/snyk-api/reference